conditional-dependencies=io.quarkiverse.langchain4j\:quarkus-langchain4j-websockets-next\:\:jar\:1.8.2
deployment-artifact=io.quarkiverse.langchain4j\:quarkus-langchain4j-core-deployment\:1.8.2
requires-quarkus-version=[3.27,)
