# Define o modelo que o Langchain4j irá invocar no Ollama.
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b-cloud

# Define o tempo limite para as chamadas ao Ollama.
quarkus.langchain4j.ollama.timeout=60s

# Define o caminho para os arquivos de RAG.
quarkus.langchain4j.easy-rag.path=src/main/resources/rag

# Habilita o log das requisições e respostas do Langchain4j.
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true